"""name

Revision ID: 1874951c5790
Revises: f56445564a7e
Create Date: 2022-05-10 15:14:08.980130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1874951c5790'
down_revision = 'f56445564a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'puzzle', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puzzle', type_='unique')
    op.drop_column('puzzle', 'name')
    # ### end Alembic commands ###
