"""empty message

Revision ID: ac0267f9235d
Revises: 1874951c5790
Create Date: 2022-05-17 22:28:22.737034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0267f9235d'
down_revision = '1874951c5790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scores_array', sa.String(length=3000), nullable=True))
    op.add_column('user', sa.Column('difficulty_dict', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'difficulty_dict')
    op.drop_column('user', 'scores_array')
    # ### end Alembic commands ###
