"""empty message

Revision ID: f56445564a7e
Revises: 625cca414b47
Create Date: 2022-05-10 14:43:56.403343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56445564a7e'
down_revision = '625cca414b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzles')
    op.create_index(op.f('ix_puzzle_difficulty'), 'puzzle', ['difficulty'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puzzle_difficulty'), table_name='puzzle')
    op.create_table('puzzles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('index', sa.VARCHAR(length=250), nullable=False),
    sa.Column('color', sa.VARCHAR(length=250), nullable=False),
    sa.Column('diff', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
